apiVersion: v1
kind: Service
metadata:
  name: ecommerce-backend
  labels:
    app: ecommerce
    tier: backend
spec:
  type: NodePort
  selector:
    app: ecommerce
    tier: backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
